package(default_visibility=["//visibility:public"])

filegroup(
    name = "controls",
    srcs = ["controls.textpb"],
)

filegroup(
    name = "content",
    srcs = [
        "__init__.py"
    ] + glob([
        "zelda2/*.py",
    ]),
)
