package(default_visibility = ["//visibility:public"])

filegroup(
    name = "controls",
    srcs = ["controls.textpb"],
)

filegroup(
    name = "content",
    srcs = glob([
        "*.py",
        "zelda2/*.py",
    ]),
)
