package(default_visibility = ["//visibility:public"])
cc_library(
    name = "vrc7_audio",
    deps = [
        ":emu2413",
    ],
)

cc_library(
    name = "emu2413",
    hdrs = [
        "emu2413.h",
    ],
    srcs = [
        "emu2413.c",
    ],
)

#cc_library(
#    name = "ym2413",
#    hdrs = [
#        "ym2413.h",
#    ],
#    srcs = [
#        "ym2413.c",
#    ],
#)
