package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "pack_config",
    srcs = ["pack_config.cc"],
    deps = [
        "//external:gflags",
        "//proto:config",
        "//util:config",
    ],
)
